/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Archivedorders_Create = require('./code/before-archivedorders-create');
const before_Users_Create = require('./code/before-users-create');
const before_Locations_Create = require('./code/before-locations-create');

class planet9ApplicationsSrv extends LCAPApplicationService {
    async init() {

        this.before('CREATE', 'ArchivedOrders', async (request) => {
            await before_Archivedorders_Create(request);
        });

        this.before('CREATE', 'Users', async (request) => {
            await before_Users_Create(request);
        });

        this.before('CREATE', 'Locations', async (request) => {
            await before_Locations_Create(request);
        });

        return super.init();
    }
}


module.exports = {
    planet9ApplicationsSrv
};